### ISSUE TITLE
[feature request] Ability to not create default logger

### ISSUE THREAD

**Issue by thom-nic** [reidmorrison/rails_semantic_logger#8]
I'm using semantic logger and trying to get my app to only log to stdout, not the default "log/production.log" file.  It seems that creating a config.logger wasn't enough, SemanticLogger apparently looks at `config.paths['log']` and creates a new logger from the first path there.  If I set the value to `nil` I get errors so best I can do is `/dev/null`. Although that means all log messages are still going through the formatter proc so it's not exactly a no-op.

**Comment by reidmorrison** [comment]
I suspect you will have to use the `semantic_logger` gem directly and bypass `rails_semantic_logger`, then implement your own initializer that unplugs the default rails logger, similar to: https://github.com/reidmorrison/rails_semantic_logger/blob/master/lib/rails_semantic_logger/railtie.rb
And then add the stdout logger instead of the file logger:
```ruby
SemanticLogger.add_appender(STDOUT)
```

If you don't mind having some of the startup messages going to the log file, then one could create a rails initializer with:
```ruby
# Remove previously registered appenders
SemanticLogger.appenders.each {|a| SemanticLogger.remove_appender(a)}
# Add a new appender to log to stdout
SemanticLogger.add_appender(STDOUT)
```

**Comment by thom-nic** [comment]
Yup I actually did add a line in my semantic_logger initializer to iterate through and remove all the default appenders just like that example.  I don't really feel like copying all of the other railtie logic where  SemanticLogger replaces all of the default loggers so I'm just going to leave it at that.  Thanks!
